image_width: 1280
image_height: 1024
camera_name: mv_camera
camera_matrix:
  rows: 3
  cols: 3
  data: [1088.05959,    0.     ,  646.65131,
            0.     , 1088.35067,  510.69345,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.471096, 0.203154, 0.000658, -0.000647, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [879.21931,   0.     , 648.57171,   0.     ,
           0.     , 960.85185, 511.24148,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
